### ISSUE TITLE
Is there a pretrained model?

### ISSUE THREAD

**Issue by MahmoudElkhateeb** [minar09/Fashion-Clothing-Parsing#3]
Hello,

I want to ask if there's a pretrained model? and if the paper is released or not ?

**Comment by minar09** [comment]
Hello @MahmoudElkhateeb , I am sorry to say that the paper is not released yet, hence we haven't released a pretrained model. Sorry for your inconvenience. Thank you.

**Comment by levindabhi** [comment]
Hello @minar09 ,
I would like to know if you have any plans in near future to release pre-trained model?

**Comment by minar09** [comment]
Hi @levindabhi, since I am not working on this anymore so there's very little chance of that. Also, this repository could be considered a less performance model compared to the more recent works. I would suggest trying with newer ones if possible.
