### ISSUE TITLE
Data Structure to train based on CFPD dataset

### ISSUE THREAD

**Issue by juanesfonsecan** [minar09/Fashion-Clothing-Parsing#4]
Hi! I am trying to use the repository with the CFPD dataset. I currently have all the images in a single folder, but I am not sure how should I distribute them in training, validation and test folders based on the .mat file.

I made some changes but I am having this error in the 311 line in FCN.py
ValueError: Cannot feed value of shape (110, 224, 224, 3, 1) for Tensor 'annotation:0', which has shape '(?, 224, 224, 1)'

Do you know what could be happening? How can I have the image tensor with the right shape?

Thank you!

**Comment by minar09** [comment]
Hi @juanesfonsecan , thank you for your question.
Actually, CFPD dataset has some more pre-processing steps before you can use it for train/test/validation.  When you download it, its just all images in one folder and one .mat file for annotations. There are some scripts you need to run to convert annotations into label images, and make separate directories with images and labels.
I have another repository which you can follow for processing CFPD dataset: https://github.com/minar09/dataset-CFPD-windows

Please let me know if you need more clarification. Thank you.
